name: Build and Push Docker Image

on:
  push:
    branches: ["main"]      # 监听 main 分支
  workflow_dispatch:        # 支持手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 登录 Docker Hub
      #    这里使用你刚刚更新的 Access Token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # 这里应该是 Access Token

      # 3. 获取短 commit hash
      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 4. 构建并推送到 Docker Hub
      #    使用 docker/build-push-action 整合构建和推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Docker build 的上下文路径，. 表示当前目录
          file: ./docker/Dockerfile  # 指定 Dockerfile 路径
          push: true  # 明确表示需要推送到仓库
          tags: |     # 添加多个标签
            ${{ secrets.DOCKER_USERNAME }}/lsky-plus:${{ steps.vars.outputs.COMMIT_HASH }}
            ${{ secrets.DOCKER_USERNAME }}/lsky-plus:latest
