name: Build and Push Multi-platform Docker Image

on:
  push:
    branches: ["main"]      # 监听 main 分支
  workflow_dispatch:        # 支持手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # ==========================================================
      # [新增步骤 1] 设置 QEMU 模拟器
      # 这是让 AMD64 架构的 Runner 能够构建 ARM64 镜像的关键
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # [新增步骤 2] 设置 Docker Buildx
      # 这是创建和使用多平台构建器的关键
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # ==========================================================

      # 2. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 获取短 commit hash
      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 4. 构建并推送到 Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          # [修改] 增加 platforms 参数，指定要构建的平台
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/lsky-plus:${{ steps.vars.outputs.COMMIT_HASH }}
            ${{ secrets.DOCKER_USERNAME }}/lsky-plus:latest
