name: Build and Push Docker Image

on:
  push:
    branches: ["main"]     # 监听 main 分支
  workflow_dispatch:       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 登出 Docker（防止缓存）
      - name: Logout Docker
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
#        run: docker logout

      # 3️⃣ 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ 获取 commit hash，作为 Docker tag
      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 5️⃣ 构建 Docker 镜像（Dockerfile 在 docker/ 目录）
      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/lsky-plus:${{ env.COMMIT_HASH }} .

      # 6️⃣ 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lsky-plus:${{ env.COMMIT_HASH }}

      # 7️⃣ 推送 latest 标签（可选）
      - name: Push Latest Tag
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/lsky-plus:${{ env.COMMIT_HASH }} ${{ secrets.DOCKER_USERNAME }}/lsky-plus:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lsky-plus:latest
